# Generated by Django 6.0 on 2025-12-30 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('board', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('board', models.JSONField()),
                ('encoded_board', models.JSONField()),
                ('moves_min_num', models.PositiveIntegerField()),
                ('disabled_nodes', models.JSONField(default=dict)),
                ('outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rotatly.outline')),
            ],
        ),
    ]
