# Generated by Django 6.0 on 2026-01-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotatly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='fixed_areas',
            field=models.JSONField(default=dict),
        ),
    ]
