# Generated by Django 6.0 on 2026-01-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotatly', '0002_game_fixed_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='disabled_nodes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='game',
            name='fixed_areas',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
