# Generated by Django 6.0 on 2026-01-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotatly', '0003_alter_game_disabled_nodes_alter_game_fixed_areas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='Daily',
        ),
    ]
