# Generated by Django 6.0 on 2026-01-09 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotatly', '0004_rename_game_daily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='index',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.JSONField()),
                ('encoded_board', models.JSONField()),
                ('moves_min_num', models.PositiveIntegerField()),
                ('disabled_nodes', models.JSONField(blank=True, default=dict)),
                ('fixed_areas', models.JSONField(blank=True, default=dict)),
                ('index', models.CharField(db_index=True, max_length=8)),
                ('outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rotatly.outline')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
