# Generated by Django 6.0 on 2026-01-21 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('board', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.JSONField()),
                ('encoded_board', models.JSONField()),
                ('moves_min_num', models.PositiveIntegerField()),
                ('disabled_nodes', models.JSONField(blank=True, default=dict)),
                ('fixed_areas', models.JSONField(blank=True, default=dict)),
                ('index', models.PositiveIntegerField(db_index=True)),
                ('outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.outline')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.JSONField()),
                ('encoded_board', models.JSONField()),
                ('moves_min_num', models.PositiveIntegerField()),
                ('disabled_nodes', models.JSONField(blank=True, default=dict)),
                ('fixed_areas', models.JSONField(blank=True, default=dict)),
                ('index', models.CharField(db_index=True, max_length=8)),
                ('outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.outline')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
